services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testannon-app
    volumes:
      - .:/var/www/html  # Mounts the current directory to /var/www/html in the container
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: testannon-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: testannon-nginx
    ports:
      - "8000:80"  # Maps port 80 in the container to port 8000 on the host
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
